CREATE TABLE ATIVIDADE (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ONDA_ID INTEGER UNSIGNED NOT NULL,
  TAREFA_ID INTEGER UNSIGNED NOT NULL,
  USUARIO_ID INTEGER UNSIGNED NOT NULL,
  HORA_INICIO TIME NULL,
  HORA_FIM TIME NULL,
  REGISTRO DATE NULL,
  PRIMARY KEY(ID),
  INDEX SEPARACAO_FKIndex1(USUARIO_ID),
  INDEX ATIVIDADE_FKIndex2(TAREFA_ID),
  INDEX ATIVIDADE_FKIndex3(ONDA_ID)
);

CREATE TABLE META (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  META FLOAT(3,2) NULL,
  SITUACAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE ONDA (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ONDA INTEGER UNSIGNED NULL,
  TOTAL_PEDIDO INTEGER UNSIGNED NULL,
  TOTAL_PRODUTO INTEGER UNSIGNED NULL,
  TOTAL_PEDIDO_FIM INTEGER UNSIGNED NULL,
  TOTAL_PRODUTO_FIM INTEGER UNSIGNED NULL,
  SITUACAO VARCHAR(10) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE PERFORMANCE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ATIVIDADE_ID INTEGER UNSIGNED NOT NULL,
  PERFORMANCE FLOAT(3,2) NULL,
  ALCANCADO FLOAT(3,2) NULL,
  REGISTRO DATE NULL,
  PRIMARY KEY(ID),
  INDEX DESEMPENHO_FKIndex1(ATIVIDADE_ID)
);

CREATE TABLE QUEBRA (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ATIVIDADE_ID INTEGER UNSIGNED NOT NULL,
  SEPARADOR VARCHAR() NULL,
  SOBRA INTEGER UNSIGNED NULL,
  FALTA INTEGER UNSIGNED NULL,
  OPERADOR VARCHAR NULL,
  REGISTRO DATE NULL,
  ONDA INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX QUEBRA_FKIndex1(ATIVIDADE_ID)
);

CREATE TABLE TAREFA (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  META_ID INTEGER UNSIGNED NOT NULL,
  NOME VARCHAR(10) NULL,
  DESCRIÇÃO VARCHAR(60) NULL,
  REGISTRO DATE NULL,
  SITUACAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX TAREFA_FKIndex1(META_ID)
);

CREATE TABLE USUARIO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FK_EVINOPS INTEGER UNSIGNED NULL,
  NOME VARCHAR(50) NULL,
  EM_ATIVIDADE INTEGER UNSIGNED NULL,
  SITUACAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID)
);


