CREATE TABLE MENU (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PERMISSAO_ID INTEGER UNSIGNED NOT NULL,
  MENU VARCHAR(20) NULL,
  TAG VARCHAR(20) NULL,
  POSICAO INTEGER UNSIGNED NULL,
  LINK VARCHAR(50) NULL,
  SUBMENU CHAR NULL,
  LIBERADO CHAR NULL,
  ATIVO CHAR NULL,
  PRIMARY KEY(ID),
  INDEX MENU_FKIndex1(PERMISSAO_ID)
);

CREATE TABLE MENU_ITEM (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PERMISSAO_ID INTEGER UNSIGNED NOT NULL,
  MENU_ID INTEGER UNSIGNED NOT NULL,
  ITEM VARCHAR(20) NULL,
  POSICAO INTEGER UNSIGNED NULL,
  LINK VARCHAR(50) NULL,
  LIBERADO CHAR NULL,
  ATIVO CHAR NULL,
  PRIMARY KEY(ID),
  INDEX MENU_ITEM_FKIndex1(MENU_ID),
  INDEX MENU_ITEM_FKIndex2(PERMISSAO_ID)
);
#Menu
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Início','inicio',1,'home.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Início','inicio',1,'home.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Início','inicio',1,'home.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Início','inicio',1,'home.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Dashboard','dashboard',2,'dashboard-private.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Dashboard','dashboard',3,'dashboard.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Dashboard','dashboard',3,'dashboard.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Dashboard','dashboard',3,'dashboard.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Meta','meta',4,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Meta','meta',4,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Meta','meta',4,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Meta','meta',4,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Desempenho','desempenho',5,'', 's', 'n', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Desempenho','desempenho',5,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Desempenho','desempenho',5,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Desempenho','desempenho',5,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Feedback','feedback',6,'', 's', 'n', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Feedback','feedback',6,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Feedback','feedback',6,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Feedback','feedback',6,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Relatórios','relatorios',7,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Relatórios','relatorios',7,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Relatórios','relatorios',7,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Relatórios','relatorios',7,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Configurações','configuracoes',8,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Configurações','configuracoes',8,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Configurações','configuracoes',8,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Configurações','configuracoes',8,'', 's', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(1, 'Sair','sair',9,'logout.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(2, 'Sair','sair',9,'logout.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(3, 'Sair','sair',9,'logout.php', 'n', 's', 's');
INSERT INTO MENU(PERMISSAO_ID, MENU, TAG, POSICAO, LINK, SUBMENU, LIBERADO, ATIVO) VALUES(4, 'Sair','sair',9,'logout.php', 'n', 's', 's');
#Item de menu Meta permissão usuário
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,9,'Consultar',1,'goal-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,9,'Inserir',2,'goal-insert.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,9,'Atualizar',3,'goal-update.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,9,'Remover',4,'goal-remove.php', 'n', 's');
#Item de menu Meta permissão líder
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,10,'Consultar',1,'goal-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,10,'Inserir',2,'goal-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,10,'Atualizar',3,'goal-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,10,'Remover',4,'goal-remove.php', 's', 's');
#Item de menu Meta permissão gestor
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,11,'Consultar',1,'goal-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,11,'Inserir',2,'goal-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,11,'Atualizar',3,'goal-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,11,'Remover',4,'goal-remove.php', 's', 's');
#Item de menu Meta permissão admin
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,12,'Consultar',1,'goal-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,12,'Inserir',2,'goal-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,12,'Atualizar',3,'goal-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,12,'Remover',4,'goal-remove.php', 's', 's');
#Item de menu Desempenho usuário
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,13,'Consultar',1,'report-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,13,'Inserir',2,'report-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,13,'Atualizar',3,'report-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,13,'Remover',4,'report-remove.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,13,'Pedente',5,'report-pedant.php', 's', 's');
#Item de menu Desempenho líder
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,14,'Consultar',1,'report-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,14,'Inserir',2,'report-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,14,'Atualizar',3,'report-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,14,'Remover',4,'report-remove.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,14,'Pedente',5,'report-pedant.php', 's', 's');
#Item de menu Desempenho gestor
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,15,'Consultar',1,'report-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,15,'Inserir',2,'report-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,15,'Atualizar',3,'report-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,15,'Remover',4,'report-remove.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,15,'Pedente',5,'report-pedant.php', 's', 's');
#Item de menu Desempenho admin
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,16,'Consultar',1,'report-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,16,'Inserir',2,'report-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,16,'Atualizar',3,'report-update.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,16,'Remover',4,'report-remove.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,16,'Pedente',5,'report-pedant.php', 's', 's');
#Item de menu Feedback usuário
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,17,'Aprovar',1,'feedback-approval.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,17,'Enviar',2,'feedback-insert.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,17,'Solicitar',3,'feedback-request.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,17,'Consultar',4,'feedback-query.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,17,'Avaliação',5,'feedback-agree-evaluation.php', 'n', 's');
#Item de menu Feedback líder
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,18,'Aprovar',1,'feedback-approval.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,18,'Enviar',2,'feedback-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,18,'Solicitar',3,'feedback-request.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,18,'Consultar',4,'feedback-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,18,'Avaliação',5,'feedback-agree-evaluation.php', 's', 's');
#Item de menu Feedback gestor
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,19,'Aprovar',1,'feedback-approval.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,19,'Enviar',2,'feedback-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,19,'Solicitar',3,'feedback-request.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,19,'Consultar',4,'feedback-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,19,'Avaliação',5,'feedback-agree-evaluation.php', 's', 's');
#Item de menu Feedback admin
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,20,'Aprovar',1,'feedback-approval.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,20,'Enviar',2,'feedback-insert.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,20,'Solicitar',3,'feedback-request.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,20,'Consultar',4,'feedback-query.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,20,'Avaliação',5,'feedback-agree-evaluation.php', 's', 's');
#Item de menu Relatórios usuário
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,21,'Gestão',1,'report.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,21,'Individual',2,'report-private.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,21,'SQL',3,'sql-query.php', 'n', 's');
#Item de menu Relatórios líder
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,22,'Gestão',22,'report.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,22,'Individual',22,'report-private.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,22,'SQL',22,'sql-query.php', 'n', 's');
#Item de menu Relatórios gestor
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,23,'Gestão',1,'report.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,23,'Individual',2,'report-private.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,23,'SQL',3,'sql-query.php', 'n', 's');
#Item de menu Relatórios admin
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,24,'Gestão',1,'report.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,24,'Individual',2,'report-private.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,24,'SQL',3,'sql-query.php', 's', 's');
#Item de menu Configurações usuário
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,25,'Cadastro',1,'register.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,25,'Opções',2,'options.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,25,'Permissões',3,'options.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,25,'Backup',4,'backup.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(1,25,'Reportar bug',5,'contact.php', 's', 's');
#Item de menu Configurações líder
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,26,'Cadastro',1,'register.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,26,'Opções',2,'options.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,26,'Permissões',3,'options.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,26,'Backup',4,'backup.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(2,26,'Reportar bug',5,'contact.php', 's', 's');
#Item de menu Configurações gestor
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,27,'Cadastro',1,'register.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,27,'Opções',2,'options.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,27,'Permissões',3,'options.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,27,'Backup',4,'backup.php', 'n', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(3,27,'Reportar bug',5,'contact.php', 's', 's');
#Item de menu Configurações admin
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,28,'Cadastro',1,'register.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,28,'Opções',2,'options.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,28,'Permissões',3,'options.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,28,'Backup',4,'backup.php', 's', 's');
INSERT INTO MENU_ITEM (PERMISSAO_ID, MENU_ID, ITEM, POSICAO, LINK, LIBERADO, ATIVO) VALUES(4,28,'Reportar bug',5,'contact.php', 's', 's');
