<?php
session_start();
include('connection.php');
//QUERY'S USADAS EM REPORT.PHP//
/*DASHBOARD DESEMPENHO DA EMPRESA*/
$g1="SELECT TRUNCATE(AVG(DESEMPENHO),2)MEDIA, TRUNCATE((SELECT MIN(DESEMPENHO) FROM DESEMPENHO WHERE DESEMPENHO>0 AND REGISTRO >= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 2 MONTH),'%Y-%m'),'-20')),2)MENOR FROM DESEMPENHO 
WHERE REGISTRO >= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 2 MONTH),'%Y-%m'),'-20')
UNION ALL
SELECT TRUNCATE(AVG(DESEMPENHO),2)MEDIA, TRUNCATE((SELECT MIN(DESEMPENHO) FROM DESEMPENHO WHERE DESEMPENHO>0 AND REGISTRO >= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 MONTH),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 1 MONTH),'%Y-%m'),'-20')),2)MENOR FROM DESEMPENHO 
WHERE REGISTRO >= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 2 MONTH),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 1 MONTH),'%Y-%m'),'-20')
UNION ALL
SELECT TRUNCATE(AVG(DESEMPENHO),2)MEDIA, TRUNCATE((SELECT MIN(DESEMPENHO) FROM DESEMPENHO WHERE DESEMPENHO>0 AND REGISTRO >= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(CURDATE(),'%Y-%m'),'-20')),2)MENOR FROM DESEMPENHO 
WHERE REGISTRO >= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(CURDATE(),'%Y-%m'),'-20')
UNION ALL
SELECT TRUNCATE(AVG(DESEMPENHO),2)MEDIA, TRUNCATE((SELECT MIN(DESEMPENHO) FROM DESEMPENHO WHERE DESEMPENHO>0 AND REGISTRO >= CONCAT(DATE_FORMAT(CURDATE(),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 1 MONTH),'%Y-%m'),'-20')),2)MENOR FROM DESEMPENHO 
WHERE REGISTRO >= CONCAT(DATE_FORMAT(CURDATE(),'%Y-%m'),'-21') 
AND REGISTRO <= CONCAT(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 1 MONTH),'%Y-%m'),'-20');";
/*DASHABOARD DESEMPENHO POR SEXO*/
$g3="SELECT U.SEXO, AVG(D.DESEMPENHO) MEDIA, MIN(D.DESEMPENHO) MINIMO FROM DESEMPENHO D 
INNER JOIN USUARIO U ON U.ID=D.USUARIO_ID
WHERE PRESENCA_ID<>2 AND REGISTRO>=DATE_SUB('".$_SESSION["periodo"]."-21', INTERVAL 1 MONTH) AND REGISTRO<='".$_SESSION["periodo"]."-20' ".$_SESSION["report-turno"]."
GROUP BY 1 ORDER BY MEDIA DESC";
/*DASHABOARD TOP 5 RANKGING MENSAL OPERADORES*/
$g4="SELECT U.NOME, AVG(DESEMPENHO) MEDIA FROM DESEMPENHO 
INNER JOIN USUARIO U ON U.ID=USUARIO_ID
WHERE PRESENCA_ID<>2 AND REGISTRO>=DATE_SUB('".$_SESSION["periodo"]."-21', INTERVAL 1 MONTH) AND REGISTRO<='".$_SESSION["periodo"]."-20'
GROUP BY USUARIO_ID ORDER BY MEDIA DESC LIMIT 5;";

//QUERY'S USADAS EM DASHBOARD.PHP//

/*DASHABOARD RANKGING MENSAL OPERADORES*/
$g5="SELECT U.NOME AS NOME, TRUNCATE(B.MAXIMO,2) AS MAXIMO, B.MINIMO FROM DESEMPENHO AS D, (SELECT USUARIO_ID, AVG(DESEMPENHO) MAXIMO, MIN(DESEMPENHO) MINIMO FROM DESEMPENHO WHERE REGISTRO>='2019-07-21' AND
REGISTRO<='2019-08-20' AND PRESENCA_ID<>3 GROUP BY USUARIO_ID) AS B
INNER JOIN USUARIO U ON U.ID=B.USUARIO_ID 
WHERE D.USUARIO_ID=B.USUARIO_ID AND REGISTRO>='2019-07-21' AND REGISTRO<='2019-08-20' AND B.MAXIMO>=100
GROUP BY D.USUARIO_ID ORDER BY 2 DESC LIMIT 4;";

$gdGestor="SELECT ID, NOME FROM GESTOR WHERE SITUACAO='Ativo'";
$gdAtividade="SELECT ID, NOME FROM ATIVIDADE WHERE SITUACAO='Ativo'";
$gdSetor="SELECT ID, NOME FROM SETOR WHERE SITUACAO='Ativo'";
function atividade(){
	$con = mysqli_query($phpmyadmin, $gdAtividade);
	$x=0; 
	while($atividade = $con->fetch_array()){
		$vtId[$x]=$atividade["ID"]; 
		$vtNome[$x] = utf8_encode($atividade["NOME"]);
		echo $vtNome[$x];
		$x++;		
	} 
}
	//$ajusteBD="set global sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
	//$ajustes= mysqli_query($phpmyadmin, $ajusteBD);

?>								