<?php
include('connection.php');

//QUERY'S USADAS EM DASHBOARD.PHP//

/*DASHABOARD RANKGING MENSAL OPERADORES*/
$g5="SELECT U.NOME AS NOME, TRUNCATE(B.MAXIMO,2) AS MAXIMO, B.MINIMO FROM DESEMPENHO AS D, (SELECT USUARIO_ID, AVG(DESEMPENHO) MAXIMO, MIN(DESEMPENHO) MINIMO FROM DESEMPENHO WHERE REGISTRO>='2019-07-21' AND
REGISTRO<='2019-08-20' AND PRESENCA_ID<>3 GROUP BY USUARIO_ID) AS B
INNER JOIN USUARIO U ON U.ID=B.USUARIO_ID 
WHERE D.USUARIO_ID=B.USUARIO_ID AND REGISTRO>='2019-07-21' AND REGISTRO<='2019-08-20' AND B.MAXIMO>=100
GROUP BY D.USUARIO_ID ORDER BY 2 DESC LIMIT 4;";

$gdGestor="SELECT ID, NOME FROM GESTOR WHERE SITUACAO='Ativo'";
$gdAtividade="SELECT ID, NOME FROM ATIVIDADE WHERE SITUACAO='Ativo'";
$gdSetor="SELECT ID, NOME FROM SETOR WHERE SITUACAO='Ativo'";
function atividade(){
	$con = mysqli_query($phpmyadmin, $gdAtividade);
	$x=0; 
	while($atividade = $con->fetch_array()){
		$vtId[$x]=$atividade["ID"]; 
		$vtNome[$x] = utf8_encode($atividade["NOME"]);
		echo $vtNome[$x];
		$x++;		
	} 
}
	//$ajusteBD="set global sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
	//$ajustes= mysqli_query($phpmyadmin, $ajusteBD);

?>								